pub fn error_code_to_str(code: u32) -> String {
    match code {
        0x00 => "Invalid command received in current state",
        0x01 => "Protocol mismatch between host and target",
        0x02 => "Invalid target protocol version",
        0x03 => "Invalid host protocol version",
        0x04 => "Invalid packet size received",
        0x05 => "Unexpected image ID received",
        0x06 => "Invalid image header size received",
        0x07 => "Invalid image data size received",
        0x08 => "Invalid image type received",
        0x09 => "Invalid tranmission length",
        0x0A => "Invalid reception length",
        0x0B => "General transmission or reception error",
        0x0C => "Error while transmitting READ_DATA packet",
        0x0D => "Cannot receive specified number of program headers",
        0x0E => "Invalid data length received for program headers",
        0x0F => "Multiple shared segments found in ELF image",
        0x10 => "Uninitialized program header location",
        0x11 => "Invalid destination address",
        0x12 => "Invalid data size received in image header",
        0x13 => "Invalid ELF header received",
        0x14 => "Unknown host error received in HELLO_RESP",
        0x15 => "Timeout while receiving data",
        0x16 => "Timeout while transmitting data",
        0x17 => "Invalid mode received from host",
        0x18 => "Invalid memory read access",
        0x19 => "Host cannot handle read data size requested",
        0x1A => "Memory debug not supported",
        0x1B => "Invalid mode switch",
        0x1C => "Failed to execute command",
        0x1D => "Invalid parameter passed to command execution",
        0x1E => "Unsupported client command received",
        0x1F => "Invalid client command received for data response",
        0x20 => "Failed to authenticate hash table",
        0x21 => "Failed to verify hash for a given segment of ELF image",
        0x22 => "Failed to find hash table in ELF image",
        0x23 => "Target failed to initialize",
        0x24 => "Failed to authenticate generic image",
        0x25 => "Invalid ELF hash table size.  Too bit or small.",
        0x26 => "Invalid IMG Hash Table Size",
        0x27 => "Enumeration failed",
        0x28 => "Hardware Bulk transfer error",
        _ => "[unknown error]",
    }
    .to_string()
}
